apps:
  name: test
  script: app.js
  watch: false
  merge_logs: true
  instances: 0
  exec_mode: cluster
  autorestart: true
  exec_interpreter: node
  max_memory_restart: 300M
  env:
    NODE_ENV: production
    NODE_APP_INSTANCE: production
  env_development:
    NODE_ENV: development
