apps:
  name: test
  script: app.js
  watch: true
  merge_logs: true
  instances: 0
  exec_mode: cluster
  autorestart: true
  exec_interpreter: node
  env:
    NODE_ENV: production
  env_development:
    NODE_ENV: development
